# azure-pipelines.yml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: ServicePrincipalId
  value: ''
- name: Azure_Subscription
  value: ''
- name: ServicePrincipalKey
  value: ''

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '<Your Azure Subscription Name>'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login -u $(ServicePrincipalId) -p $(ServicePrincipalKey)
      az appservice plan create --name myAppServicePlan --resource-group myResourceGroup --sku S1 --is-linux
      az webapp create --resource-group myResourceGroup --plan myAppServicePlan --name myWebApp --runtime "node|12.x" --deployment-local-git
  name: Create_Azure_Resources

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)'
    artifactName: 'drop'

- task: DeploymentGroupJob@2
  inputs:
    ConnectedServiceName: '<Your Azure Deployment Group Name>'
    DeploymentGroup: '<Your Azure Deployment Group Name>'
    DeploymentType: 'LocalGit'
    GitCloneDirectory: '$(System.DefaultWorkingDirectory)'
    Repository: '$(System.DefaultWorkingDirectory)'
    TargetPath: '/home/site/wwwroot'
    Command: 'git clone https://github.com/<Your Repository Name>.git $(System.DefaultWorkingDirectory)'
  name: Deploy_to_Azure
